import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'case-iphone-15',
    name: 'Crystal Clear Case for iPhone 15',
    description: 'Show off your iPhone\'s design with this ultra-thin, anti-yellowing clear case.',
    price: 24.99,
    image: 'case-iphone-15',
    brand: 'Generic',
    type: 'Case',
    rating: 4.5,
    features: ['Anti-yellowing material', 'Slim profile', '10-foot drop protection'],
    reviews: [
      { id: 'r1', author: 'Jane D.', rating: 5, text: 'Love how it feels! Not bulky at all.', date: '2023-10-01' },
      { id: 'r2', author: 'John S.', rating: 4, text: 'Good case, but can be a bit slippery.', date: '2023-10-03' },
    ],
  },
  {
    id: 'case-samsung-s23',
    name: 'Leather Wallet Case for Galaxy S23',
    description: 'A stylish and functional vegan leather case with card slots for your essentials.',
    price: 39.99,
    image: 'case-samsung-s23',
    brand: 'Samsung',
    type: 'Case',
    rating: 4.8,
    features: ['Premium vegan leather', 'Holds 3 cards', 'Magnetic closure'],
    reviews: [
      { id: 'r3', author: 'Emily R.', rating: 5, text: 'So convenient! I don\'t need to carry a wallet anymore.', date: '2023-09-15' },
    ],
  },
  {
    id: 'charger-anker-pd',
    name: 'Anker 100W GaN Fast Charger',
    description: 'Charge your laptop, phone, and tablet all at once with this powerful and compact charger.',
    price: 75.00,
    image: 'charger-anker-pd',
    brand: 'Anker',
    type: 'Charger',
    rating: 4.9,
    features: ['GaN technology', '2 USB-C and 2 USB-A ports', 'Intelligent power allocation'],
    reviews: [
      { id: 'r4', author: 'Mike T.', rating: 5, text: 'A game changer for travel. One charger for everything.', date: '2023-10-05' },
    ],
  },
  {
    id: 'charger-samsung-wireless',
    name: 'Samsung Fast Wireless Charger Duo',
    description: 'Charge your Galaxy phone and smartwatch simultaneously with this sleek wireless charging pad.',
    price: 89.99,
    image: 'charger-samsung-wireless',
    brand: 'Samsung',
    type: 'Charger',
    rating: 4.2,
    features: ['Charges 2 devices', 'Fast Wireless Charging 2.0', 'Built-in cooling fan'],
    reviews: [
      { id: 'r5', author: 'Chris P.', rating: 4, text: 'Works well, but a bit picky with phone placement.', date: '2023-09-20' },
    ],
  },
  {
    id: 'cable-apple-lightning',
    name: 'Apple USB-C to Lightning Cable (1m)',
    description: 'Official Apple cable for fast charging and syncing your iPhone, iPad, or iPod.',
    price: 19.00,
    image: 'cable-apple-lightning',
    brand: 'Apple',
    type: 'Cable',
    rating: 4.6,
    features: ['Official Apple product', 'Supports Power Delivery', 'Durable design'],
    reviews: [
      { id: 'r6', author: 'Sarah L.', rating: 5, text: 'You can\'t beat the original. Works perfectly.', date: '2023-10-10' },
    ],
  },
  {
    id: 'cable-anker-usbc',
    name: 'Anker PowerLine III USB-C Cable (6ft)',
    description: 'A super-durable, nylon-braided USB-C cable that supports high-speed charging.',
    price: 15.99,
    image: 'cable-anker-usbc',
    brand: 'Anker',
    type: 'Cable',
    rating: 4.9,
    features: ['Nylon-braided exterior', '25,000-bend lifespan', 'Supports 100W charging'],
    reviews: [
      { id: 'r7', author: 'David B.', rating: 5, text: 'This cable is built like a tank. Worth every penny.', date: '2023-09-01' },
    ],
  },
  {
    id: 'sp-iphone-15',
    name: 'Tempered Glass Protector for iPhone 15',
    description: 'Protect your screen from scratches and impacts with this easy-to-install glass protector.',
    price: 12.99,
    image: 'sp-iphone-15',
    brand: 'Generic',
    type: 'Screen Protector',
    rating: 4.3,
    features: ['9H hardness tempered glass', 'Oleophobic coating', 'Includes alignment frame'],
    reviews: [
      { id: 'r8', author: 'Olivia W.', rating: 4, text: 'Installation was easy with the frame, but it got a dust bubble.', date: '2023-10-08' },
    ],
  },
  {
    id: 'sp-samsung-s23',
    name: 'Film Screen Protector for Galaxy S23',
    description: 'A flexible film protector that is fully compatible with the ultrasonic fingerprint sensor.',
    price: 14.99,
    image: 'sp-samsung-s23',
    brand: 'Generic',
    type: 'Screen Protector',
    rating: 4.7,
    features: ['Fingerprint sensor compatible', 'Self-healing technology', 'Case-friendly design'],
    reviews: [
      { id: 'r9', author: 'Ben C.', rating: 5, text: 'Finally, a screen protector that works with the fingerprint reader!', date: '2023-09-25' },
    ],
  },
];
